version: "3"
services:

  db:
    image: postgres:11.0
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
    hostname: db

  web:
    build: .
    ports:
      - 0.0.0.0:80:80
    environment:
      - DATABASE_URL=pgsql://admin:password@db:5432/dauco
      - DRIVER='pdo_pgsql'
      - CHARSET=utf8
      - COLLATE=utf8_unicode_ci
    depends_on:
      - db